eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
---
#just provide a fallback
spring:
  profiles: default
words: default

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
wordConfig:
  words: staring,great,green,suspicious,scary
---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog  

---
spring:
  profiles: cold-noun
words: icicle,refrigerator,blizzard,snowball
